em tty + ytdl & album-split from linbox + nvim->vim

diff --git a/scripts/album-split b/scripts/album-split
--- a/scripts/album-split
+++ b/scripts/album-split
@@ -1,36 +1,49 @@
-#!/bin/sh
+#!/bin/bash
 
-# DIR="$HOME/dev/ydl/black/Black_Metal_Promotion/Caladan_Brood/Echoes_of_Battle"
-DELIM="<>"
 DIR="$1"
-[ ! -d "$DIR" ] && printf "Expecting a directory but received a file instead. Exiting...\n" && exit 1
+source="$2"
+tracklist="$3"
+DELIM="$4"
+EXT="$5"
 
-mp3="$(ls "$DIR/"*.mp3)"
-[ "$(echo "$mp3" | wc -l)" -gt 1 ] && printf "No multi-file functionality implemented yet \nPass in one .mp3 file at a time\n" && exit 1
+[[ ! -d "$DIR" ]] && printf "[ERROR]: Argument \$1 should be a directory. Exiting...\n" && exit 1
+[[ ! -e "$source" ]] && printf "[ERROR]: Argument \$2 should be audio source but was not found. Exiting...\n" && exit 1
+[[ ! -e "$tracklist" ]] && printf "[ERROR]: Argument \$3 should be tracklist but was not found. Exiting...\n" && exit 1
+[[ -z "$DELIM" || -z "$EXT" ]] && printf "[ERROR]: Arguments \$4 and \$5 should be DELIM and EXT but one or more is empty. Exiting...\n" && exit 1
 
-tracklist="$(ls "$DIR/"*.tracklist)"
-tracks="$(cat "$tracklist" | wc -l)"
+num_tracks="$(cat "$tracklist" | wc -l)"
+tracks_dir="$DIR/tracks"
+
+# [[ -d $dir && $(ls $dir | wc -l) -gt 0 ]] && printf "[ERROR]: [$tracks_dir] directory already exists and is not empty. Exiting...\n" && exit 1
 
 i=1
 cat "$tracklist" | while read l; do
-	title="$(echo "$l" | awk -F "$DELIM" '{print $1}')"
-	ts="$(echo "$l" | awk -F "$DELIM" '{print $2}')"
-	start="$(echo $ts | awk -F "-" '{print $1}')"
-	end="$(echo $ts | awk -F "-" '{print $2}')"
-	# echo "$i/$tracks. $mp3 --> $DIR/$title"
-	# ffmpeg -y -nostdin -hide_banner -loglevel error -ss "$start" -to "$end" -i "$mp3" -c:v copy "$DIR/$title.mp3"
+    title="$(echo "$l" | awk -F "$DELIM" '{print $1}' | sed 's/ /_/g').$EXT"
+    ts="$(echo "$l" | awk -F "$DELIM" '{print $2}')"
+    artist="$(echo "$l" | awk -F "$DELIM" '{print $3}')"
 
-	mkdir -vp "$DIR/Tracks"
-	printf "$i/$tracks. Processing %s -> %s..." "$(basename "$mp3")" "$title.mp3"
-	ffmpeg \
-		-y \
-		-nostdin \
-		-hide_banner -loglevel error \
-		-ss "$start" -to "$end" \
-		-i "$mp3" \
-		-c:v copy \
-		-metadata track="$i/$tracks" \
-		"$DIR/Tracks/$title.mp3"
-	printf "Done\n"
-	i=$((i+1))
+    [[ -z "$artist" ]] && artist="Unknown"
+
+    start="$(echo $ts | awk -F "-" '{print $1}')"
+    end="$(echo $ts | awk -F "-" '{print $2}')"
+
+    mkdir -vp "$tracks_dir"
+
+    # Track already exists and has a size greater than 0
+    [[ -f "$tracks_dir/$title" && $(du "$tracks_dir/$title" | awk '{print $1}') -gt 0 ]] && i=$((i+1)) && continue
+
+    printf "[INFO]: $i/$num_tracks. Processing %s -> %s by (%s)...\n" "$(basename "$source")" "$title" "$artist"
+
+    ffmpeg \
+	-y \
+	-nostdin \
+	-hide_banner -loglevel error \
+	-ss "$start" -to "$end" \
+	-i "$source" \
+	-c:v copy \
+	-metadata track="$i/$num_tracks" \
+	-metadata artist="$artist" \
+	"$tracks_dir/$title"
+
+    i=$((i+1))
 done
